name: LearnableFilter4D
train_data: /home/dpietsch/Data/.cache/Inhouse1Processed_v3
parameter_dir: /home/dpietsch/4DCT/parameters
epochs: 30
amp: False
model:
  stages:
    - type: learnable_spt4d
      count: 3
      params: [
        {
          sigma_t: 1.0, sigma_x: 0.5834, sigma_y: 0.2163, sigma_z: 0.6498,
          color_sigma: 0.4794, window_size_t: 9, pad_t: 4, window_sizes: [1, 5, 5, 5], kernel_floor: 1e-6
        },
        {
          sigma_t: 1.0, sigma_x: 0.2173, sigma_y: 0.2432, sigma_z: 0.2426,
          color_sigma: 0.3195, window_size_t: 9, pad_t: 4, window_sizes: [1, 5, 5, 5], kernel_floor: 1e-6
        },
        {
          sigma_t: 1.0, sigma_x: 0.2104, sigma_y: 0.7592, sigma_z: 0.2127,
          color_sigma: 0.3521, window_size_t: 9, pad_t: 4, window_sizes: [1, 5, 5, 5], kernel_floor: 1e-6
        }
      ]
    - type: learnable_spt4d
      count: 1
      params: [
        {
          sigma_t: 1.2637, sigma_x: 1.0, sigma_y: 1.0, sigma_z: 1.0,
          color_sigma: 0.0539, pad_t: 4, window_sizes: [9, 1, 1, 1],
          kernel_floor: 1e-6
        }
      ]
optim: {lr_r: 0.005, lr_kernel: 0.05}
clamp: {sigma_min: 0.01, sigma_max: 2.0, range_min: 0.0001}
crop: {patch_size: [32, 64, 64], margin: [8, 8, 8], num_crops: 8}