name: SPBF_Filterbank_Tests_1
epochs: 10
lr_st: 0.001
lr_r: 0.001
batch_size: 1
num_spatial: 1
num_temporal: 1
train_data: /home/dpietsch/Pictures/.cache/Inhouse2Processed
validation_data: /home/dpietsch/Pictures/.cache/Inhouse1Processed

